### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/react-native-video-watermark - Not found

### ISSUE THREAD

**Issue by pperron** [sagark1510/react-native-video-watermark#1]
When trying to install, npm nor yarn can find your lib...

**Comment by sagark1510** [comment]
@pperron  Sorry you can not install it through npm.. just do
`npm install https://github.com/sagark1510/react-native-video-watermark#1.0.2`

**Comment by pperron** [comment]
Ok, will try that tonight. You have a bit more info on how to use the lib ? We pass an image to your lib, but where the image watermark will be applied ?

I tried using react-native-ffmpeg but it conflicts with an other lib I'm using (react-native-video-processing). It seems to complain about some duplicates similar .so (seen on the forums that it conflicts witn react-native-opencv too).

Yours is based on ffmpeg too ?

thanks !

**Comment by sagark1510** [comment]
@pperron No it's not ffmpeg based, due to licensing issue I had to create this library :)

Example file added in the codebase. Please check it out for how to use it.
