### ISSUE TITLE
com.github.MasayukiSuda:Mp4Composer-android:v0.3.5

### ISSUE THREAD

**Issue by vmenekos** [sagark1510/react-native-video-watermark#2]
React-native project getting this for android.
coudn't find com.github.MasayukiSuda:Mp4Composer-android:v0.3.5

**Comment by sagark1510** [comment]
@vmenekos 

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```

update your android/build.gradle file
