### ISSUE TITLE
Android passing image won't work

### ISSUE THREAD

**Issue by vmenekos** [sagark1510/react-native-video-watermark#3]
I pass image with file:// or content:// or without and never works.

**Comment by sagark1510** [comment]
@vmenekos did you check the example file? Which OS are you testing with?

**Comment by vmenekos** [comment]
@sagark1510 
on iOS it works just fine.
on Android however i pass the image that should be overlayed it fails.
To be more clear it seems it processes and saves the video but image isn't in the video written.

**Comment by vmenekos** [comment]
Somehow i got it working... i don't if it was my old phone.
But now image a lot wider than the video.

**Comment by vmenekos** [comment]
The bug was that the lib i saved the image didn't save with correct values: height/width.
Otherwise lib works great!
