### ISSUE TITLE
EXC_BAD_INSTRUCTION IOS simulator error - Crash

### ISSUE THREAD

**Issue by senolatac** [sagark1510/react-native-video-watermark#5]
When I send parameters like below:

Checking passed variables: 

Video was read from URL and stored on device like react-native.mp4:
`/Users/mobile/Library/Developer/CoreSimulator/Devices/A4FBD7DF-DC56-489F-AA7C-B119A934532D/data/Containers/Data/Application/1ECD1006-CC6C-4A14-903A-724D3D78B1CC/Documents/react-native.mp4 `

ImageMarker was read from URL and stored on device like B592874F-E000-41F5-9837-9474C74B207B.png:
`/Users/mobile/Library/Developer/CoreSimulator/Devices/A4FBD7DF-DC56-489F-AA7C-B119A934532D/data/Containers/Data/Application/1ECD1006-CC6C-4A14-903A-724D3D78B1CC/tmp/ReactNative/B592874F-E000-41F5-9837-9474C74B207B.png`

Then send it via:

```
        VideoWatermark.convert(
          videoPath,
          markImage,
          (convertedVideo) => {
            console.log(convertedVideo);
          },
        );
```

as a result app crashed. Any idea?

**Comment by senolatac** [comment]
problem is related with simulator/emulator. On real-device , it's worked.

**Comment by sagark1510** [comment]
@senolatac  sorry I was away. Thanks for closing the issue.
